apiVersion: apps/v1
kind: Deployment
metadata:
  name: lil-api-test-server-b
  namespace: jessica-tracy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lil-api-test-server-b
  template:
    metadata:
      labels:
        app: lil-api-test-server-b
    spec:
      containers:
      - name: lil-api-test-server-b
        image: 256727351604.dkr.ecr.us-east-1.amazonaws.com/jessica:lil-ap-server-b
        ports:
        - containerPort: 8081
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internet
  name: lil-api-test-server-b
  namespace: jessica-tracy
spec:
  rules:
  - host: lil-api-test-server-b.jessica-tracy.eks.staging-callrail.com
    http:
      paths:
      - backend:
          serviceName: lil-api-test-server-b
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lil-api-test-server-b
  namespace: jessica-tracy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: lil-api-test-server-b
  sessionAffinity: None
  type: ClusterIP
